services:
  - type: static
    name: file-management-system
    buildCommand: echo "No build required"
    publishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /
        destination: /index.html 